### ISSUE TITLE
No fresh animation

### ISSUE THREAD

**Issue by SLimeyMC** [UVSE-Invictus/invictus#10]
Why: idk use this as replacement fr https://www.curseforge.com/minecraft/mc-mods/not-enough-animations

**Comment by InstSnipe** [comment]
fresh animations and not enough animations are two completely different things

**Comment by InstSnipe** [comment]
also the other animation rp we have is also completely different

**Comment by SLimeyMC** [comment]
> fresh animations and not enough animations are two completely different things

Indeed they are, however they do the same thing. While not enough animation only do player animation, it is enough IMHO. They also work with real camera better (probably because it's not optifine resourcepack guh)
