### ISSUE TITLE
Mekanism ore spam

### ISSUE THREAD

**Issue by SLimeyMC** [UVSE-Invictus/invictus#14]
The amount of ore mekanism generate is causing problem, would like it to be tuned down

**Comment by PriestOfFern** [comment]
I thought you were using a custom map

**Comment by PriestOfFern** [comment]
In anycase, [try this](https://www.curseforge.com/minecraft/mc-mods/ore-tweaker?__cf_chl_tk=MsoK8Dfk_GH8eOtUF8h542mGxtO6lACA2gA1BFBIVFs-1708253008-0.0-4541)

**Comment by Bt111488** [comment]
This should be fixed once I merge the ore generation branch into main
