### ISSUE TITLE
Block entity not rendering

### ISSUE THREAD

**Issue by SLimeyMC** [UVSE-Invictus/invictus#20]
help

**Comment by PriestOfFern** [comment]
I already told you how to fix it. Downgrade embeddium to 0.2.4

**Comment by SLimeyMC** [comment]
I infact did, forgot to close the issue oops

**Comment by PriestOfFern** [comment]
making issues to close them is a very interesting thing to do

**Comment by SLimeyMC** [comment]
i make the issue before remembering that you told me that
